### PR TITLE
Scrape course catalog into database.

### PR DESCRIPTION
**Pull request by danasilver**
After migrating, run:

``` bash
node lib/scripts/scrape_catalog.js 201590  # Fall 2015
```

### CODE REVIEW

**Comment by jabillings** [comment]
Looks good. There seem to be some HTML tags in some of the scraped data from the descriptions, but I think that should be fairly easy to remove using regex or something. Also, are the courses linked to meeting times somehow? I'll probably figure out soon enough, but to streamline things I'll approve the merge anyway

**Comment by danasilver** [comment]
Each meeting is has a foreign key pointing to a courseoffering. And yeah, we can remove the tags using a HTML parser if we want.

**Comment by jabillings** [comment]
OK. Is there a way to get the meeting time from the course offering? (Sorry if this is obvious I haven't had a chance to dive into the code yet)

**Comment by danasilver** [comment]
``` js
CourseOffering.where('id', someId)
.fetch({withRelated: ['meetings']})
.then(function(courseoffering) {
  const meetings = courseoffering.related('meetings'); // or courseoffering.meetings();
});
```

**Pull request merged**
