### PR TITLE
Jb api fix

### PR DESCRIPTION
**Pull request by jabillings**
make a fix to the 'meetings' part of the API

### CODE REVIEW

**Comment by pbernasconi** [comment]
can you squash these:

``` console
git rebase -i HEAD~4
```

**Comment by jabillings** [comment]
Good enough? Not sure how to get rid of the 4 commits at the top

**Comment by danasilver** [comment]
Run that rebase command then alter the message (squash, use, whatever) like git says and it'll rebase. Then you'll have to force push the branch.

**Comment by danasilver** [comment]
Is this work in progress? @jabillings

**Comment by jabillings** [comment]
No it's just meant to be a quick fix to one bug. The commented out section is work in progress but there's only 1 line change of code that's used

**Pull request merged**
